### ISSUE TITLE
Unable to use the utility

### ISSUE THREAD

**Issue by sagarmorakhia** [Rello/HANA_XML-to-SQL#1]
Hi Rello,

This is a brilliant utility that you have created. Kudos to you for this.. 

Unfortunately, I am not a PHP guy and not able to use the utility. 

I checked with one of my colleague who knows PHP but even he was not able to use it and help me get the output. 

It would be really great if you can share some steps on how to run this utility step by step. 

Also, if there is any way we can use the online PHP editor to run the code and get the output.

I would really appreciate it if you can help me out here.. you would save me atleast 2 3 weeks worth of time. 

Thanks in advance.

**Comment by Rello** [comment]
hey.
thanks for the feedback!
try this link and let me know:
https://***hidden***/xmltosql/index.php

...I did not cover all parts in routines or unions, but I hope it can still help you for the basics. let me know...

**Comment by sagarmorakhia** [comment]
Thanks for your quick response buddy.

Awesome!!!

It worked!!!!!!! :) :) :) 

Thanks, mate. Appreciate your response. 

Any plans for Adding Union?

I have a couple of unions in a few of my scripts.

**Comment by Rello** [comment]
I don´t have the need on my side at the moment. I will see if I find some time

may I ask what you are using the converter for at the moment?

**Comment by sagarmorakhia** [comment]
So I have lots of Hana Designer views and I need to get the complete underlying query. 
Unfortunately, SAP HANA does not provide that option out of the box, so we are converting the queries manually.

**Comment by Rello** [comment]
Why?

We did it in the beginning of the Hana1 releases but now the optimizer is pretty good wo there should bot be much performance difference left - compared to the huge benefit of the graphical UI

**Comment by sagarmorakhia** [comment]
So the reason is we are migrating from HANA to Snowflake DWH. So we need to replicate the same queries and run them in Snowflake. That's why I need the underlying query. And it's a big big task to create all the queries manually looking at the designer filters, groupby etc. We have more than 100 designer queries to be converted. So if I can find some good automated option wherein I can just pass the designer XML or something and it spits the actual query, it would save a lot of time for me.

**Comment by Rello** [comment]
ok, got it.
I hope my converter will help you for some portions here1

**Comment by sagarmorakhia** [comment]
Yeah It would. :)
Thanks again mate!
